### ISSUE TITLE
Question : Output cachegrind files

### ISSUE THREAD

**Issue by Akanoa** [2dav/crabgrind#4]
Hi !

I'm pretty new with valgrind (1 hour ago ^^').

I'd like to output cachegrind file but I don't know how to manage this.

So far, I've done this:

```rust
fn run<B: Buffer>(source: Source, save_buffer: &mut B, work_buffer: &mut B) {
    let mode = cg::run_mode();
    cg::print_stacktrace!("current mode: {mode:?}");

    cg::callgrind::toggle_collect();
    cg::cachegrind::start_instrumentation();
    playground::parsers::preallocated::parser_preallocated(source, save_buffer, work_buffer)
        .unwrap();
    cg::callgrind::toggle_collect();
    cg::cachegrind::stop_instrumentation();

    if cg::monitor_command("snapshot mem.snapshot").is_ok() {
        println!("snapshot is saved to \"mem.snapshot\"");
    } else {
        println!("error")
    }
}
```

The `main` call `run` and does all heavy initialization.

I run everything with a 

```
cargo valgrind run
```

How can I achieve this ?

With valgrind I've done

```
valgrind --tool=cachegrinf my_bin
```

But it profiles the main and poluate my analysis.

Thanks

**Comment by 2dav** [comment]
Hey! By default, `Valgrind` starts to instrument the program right from its entry point. You can alter this behaviour via tool-specific command line option: 

For *callgrind*, [--collect-atstart=no](https://valgrind.org/docs/manual/cl-manual.html#opt.collect-atstart).

For *cachegrind*, [--instr-at-start=no](https://valgrind.org/docs/manual/cg-manual.html#opt.instr-at-start).

Specifying this result in disabling automatic sampling, so toggling it manually at the interest points should give you isolated measurements:

For *callgrind*,
```rust
use crabgrind as cg;

cg::callgrind::toggle_collect();
// ... code of interest ...
cg::callgrind::toggle_collect();
```

For *cachegrind*,
```rust
use crabgrind as cg;

cg::cachegrind::start_instrumentation();
// ... code of interest ...
cg::cachegrind::stop_instrumentation();
```

**Comment by Akanoa** [comment]
Hi !
Yes, the solution was to get rid off cargo-valgrind and use valgrind itself instead ^^
It works so well !
Thanks for your library ! 😁
