### ISSUE TITLE
Odd `NoValgrind` errors from `crabgrind::memcheck::mark_mem`

### ISSUE THREAD

**Issue by ctz** [2dav/crabgrind#5]
This is on x86_64 ubuntu linux 24.04 with valgrind 3.22.0-0ubuntu3, crabgrind 0.1.10, rustc 1.80.1.

`crabgrind::run_mode()`, `crabgrind::println!` and `crabgrind::monitor_command` all work, but `memcheck::mark_mem()` returns `NoValgrind`.

I can avoid that by using `callgrind::monitor_command(format!("make_memory undefined {:p} {}", input.as_ptr(), input.len())).unwrap();` which works and isn't a terrible solution.

Any ideas?

**Comment by 2dav** [comment]
-1/0 reversed indeed! Thank you.
